#!/usr/bin/env bash
if [ "$(id -u)" = "0" ]; then
    echo "This script must be run as normal user" 1>&2
    exit 1
else
    sudo rmmod ath10k_core ath10k_pci &
    sleep 3s &
    sudo modprobe ath10k_core ath10k_pci &
    sudo systemctl restart NetworkManager 
fi
