#!/usr/bin/env bash

if [ "$(id -u)" = "0" ]; then
   echo "This script must be run as normal user" 1>&2
   exit 1
fi

if [ -e /dev/sdb ] ; then
    udisksctl unmount --block-device /dev/sdb1
    udisksctl power-off -b /dev/sdb
fi

if [ -e /dev/sdc ] ; then
    udisksctl unmount --block-device /dev/sdc1
    udisksctl power-off -b /dev/sdc
fi

if [ -e /dev/sdd ] ; then
    udisksctl unmount --block-device /dev/sdd1
    udisksctl power-off -b /dev/sdd
fi
