#!/usr/bin/env bash
if [ "$(id -u)" = "0" ]; then
   echo "This script must be run as normal user" 1>&2
   exit 1
fi
cd $HOME/GitHub/00-HSTS.EXT/
python updateHostsFile.py -a -c -r && sudo systemctl restart NetworkManager
